# Generated by Django 3.2.6 on 2021-12-21 11:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20211219_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='formation',
            fields=[
                ('username', models.CharField(max_length=200)),
                ('password', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
