# Generated by Django 3.2.6 on 2021-12-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_formation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='work3.jpg', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='formation',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
