# Generated by Django 3.2.6 on 2023-03-10 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220104_1626'),
        ('projects', '0010_alter_project_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='owners',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('owners', 'projects')},
        ),
    ]
