# Generated by Django 3.2.6 on 2023-03-10 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220104_1626'),
        ('projects', '0012_alter_reviews_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='owners',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
    ]
